### ISSUE TITLE
request.queryParams("param_name") fails when request method is GET OR PUT

### ISSUE THREAD

**Issue by prestorondo** [srlk/spark-swagger#1]
Hi . First of all I wanna appreciate your effort to make this great library which makes life so much easy however, I found out that when you try to perform the following : 

// url example = /books?id=2 , request method GET
`String id = request.queryParamOrDefault("id" null);`
 or 
`String id = request.queryParam("id");`
This will always return null. First I thought it is working as intented however today I tested without this library and it worked. let me know if the issue is not clear. 
Thanks

**Comment by prestorondo** [comment]
the same issue exists with request method PUT

**Comment by srlk** [comment]
Hello @prestorondo ,

Sorry for late comment :) Have you tried using  `String id = request.params("id");` ?

**Comment by prestorondo** [comment]
Yes I tried `String id = request.params("id"); ?` as well but I get null 
however , this method is used for parameters passed in the url `('/books/:id')` where my question is about the data/body of the request `(/books?id=2)`

**Comment by srlk** [comment]
My mistake,  so clarify things

To get parameter `('/books/:id')`
You use `String id = request.params("id");`

To get `(/books?id=2)`
You use `String id = request.queryParams("id");` 

And if you need request body `request.body()` will return body as a `String`

That's how it works for me on Spark Java version 2.3. It it doesn't work out for you, can you try updating your Spark Java to latest version and report a bug to https://github.com/perwendel/spark if problem persists?

**Comment by prestorondo** [comment]
I'm using latest version of Spark (2.6.0). 
Please remember that my question is about a request with `PUT` or `GET` methods. 

> And if you need request body request.body() will return body as a String

yes but I have to handle retrieving the parameters manually which is not preferred when Spark does it automatically with `request.queryParams("id")`. As I said in my first post, this works on pure Spark but fails with this library.

**Comment by srlk** [comment]
Hello,

I upgraded to 2.6.0 ( see: 650db5673410dfacb34643ab9f9fcc149e4bfcc0 ) however I couldn't reproduce problem. I have small guess, can you verify your request is going to correct route?

**Comment by srlk** [comment]
stale issue
